### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jtornero** [cduck/morse#1]
Hello!

Under which license is this project? Can it be used for a personal project (in my case, a Twitter bot)?

Thank you very much!!

**Comment by cduck** [comment]
MIT, so yes you can.  I just added LICENSE.txt.

https://opensource.org/licenses/MIT

**Comment by jtornero** [comment]
@cduck Thanks a lot. You can see (and mostly hear) the thing here:

https://twitter.com/siempremorse

All the best,

Jorge

**Comment by cduck** [comment]
Thanks for sharing!
